### ISSUE TITLE
Error inflating class android.support.v7.internal.widget.TintCheckBox

### ISSUE THREAD

**Issue by tomcataa** [tekinarslan/AndroidMaterialDesignToolbar#5]
Thank you for sharing.

I got this error, but I couldn't figure out what's wrong.
I use Android L device.

Besides, when I initially import your project,
I need to change `<item name="android:windowNoTitle">true</item>` 
to `<item name="windowNoTitle">true</item>` in styles.xml to get rid of an error.

**Comment by hufeiya** [comment]
Yes,I have the same problem and I'm trying to figure out.

**Comment by liyzay** [comment]
I have the same problem,too.

**Comment by ChoingHyun** [comment]
I met the same problem on my MI4 device ,
I alse change <item name="android:windowNoTitle">true</item> 
to <item name="windowNoTitle">true</item>
but.. it doesn't work for me.I'm trying to find out the problem.

**Comment by Alpha-chen** [comment]
@tomcataa 
I met you the same mistakes, you solved the problem?
 when I initially import this project,
i met "java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tekinarslan.material.sample/com.tekinarslan.material.sample.SampleActivity}: java.lang.IllegalArgumentException: AppCompat does not support the current theme features"

I follow you   changeing <item name="android:windowNoTitle">true</item> 
to <item name="windowNoTitle">true</item>
but i met  Error inflating class android.support.v7.internal.widget.TintCheckBox；
